API_HOST_URL: https://successlab.ai/
ENVIRONMENT_DISPLAY_NAME: SuccessLab
ECOMMERCE_URL: https://ecommerce.successlab.ai
PLATFORM_NAME: SuccessLab
PLATFORM_DESTINATION_NAME: https://successlab.ai
FEEDBACK_EMAIL_ADDRESS: support@successlab.ai
DEBUG: true
MY_VIDEOS_ENABLED: true
COURSE_VIDEOS_ENABLED: true
ANNOUNCEMENTS_ENABLED: true
COURSE_SHARING_ENABLED: true
BADGES_ENABLED: true
DOWNLOAD_TO_SD_CARD_ENABLED: true
TAB_LAYOUTS_ENABLED: true
PUSH_NOTIFICATIONS: true
USER_PROFILES_ENABLED: true
DISCUSSIONS_ENABLED: true
DISCUSSIONS_ENABLE_PROFILE_PICTURE_PARAM: true
IAP_ENABLED: false
CERTIFICATES_ENABLED: true
YOUTUBE_PLAYER:
  ENABLED: true
  API_KEY: DEVELOPER_KEY
API_URL_VERSION:
  BLOCKS: v1
OAUTH_CLIENT_ID: wmoEzP2IdgPxGfvPPwfihQfFWkSAmqht4pe306jY
