# See docs: https://openedx.atlassian.net/wiki/spaces/LEARNER/pages/48792067/App+Configuration+Flags
API_HOST_URL: 'https://successlab.ai'
ECOMMERCE_URL: 'https://ecommerce.successlab.ai'
ENVIRONMENT_DISPLAY_NAME: 'SuccessLab'
PLATFORM_NAME: 'SuccessLab'
PLATFORM_DESTINATION_NAME: 'https://successlab.ai'
FEEDBACK_EMAIL_ADDRESS: 'support@successlab.ai'
OAUTH_CLIENT_ID: 'wmoEzP2IdgPxGfvPPwfihQfFWkSAmqht4pe306jY'
IAP_ENABLED: false
API_URL_VERSION:
  BLOCKS: 'v1'
  REGISTRATION: 'v1'
COURSE_VIDEOS_ENABLED: true
CERTIFICATES_ENABLED: true
DISCUSSIONS_ENABLED: true
DISCOVERY:
  COURSE:
    TYPE: native
DOWNLOAD_TO_SD_CARD_ENABLED: true
NEW_LOGISTRATION_ENABLED: true
USER_PROFILES_ENABLED : true
VIDEO_TRANSCRIPT_ENABLED: true
APP_REWIEWS_ENABLED: true
ANNOUNCEMENTS_ENABLED: true
BADGES_ENABLED: true
COURSE_DATES_ENABLED: false
COURSE_ENROLLMENT_ENABLED: true
COURSE_VIDEO_ENABLED: false
COURSE_SHARING_ENABLED: false
DISCUSSIONS_ENABLED: true
DISCUSSIONS_ENABLE_PROFILE_PICTURE_PARAM: true
NEW_COURSE_NAVIGATION_ENABLED: true
PUSH_NOTIFICATION: true
REGISTRATION_ENABLED: true
TAB_LAYOUTS_ENABLED: true
USING_VIDEO_PIPELINE: true
VIDEO_TRANSCRIPT_ENABLED: true
WHATS_NEW_ENABLED: true

FIREBASE:
  ENABLED: true
  ANALYTICS_SOURCE: 'firebase'
  CLOUD_MESSAGING_ENABLED: true
  PROJECT_NUMBER: '570777364216'
  PROJECT_ID: 'suceab-e2e56'
  OAUTH_CLIENT_ID: '570777364216-a2bfnc2h1oto8n4c6e9mf3aq7akk6jh0.apps.googleusercontent.com'
  CURRENT_KEY: 'AIzaSyA5D091QNgvf-Ev1VMscjP6RORQFbo4Hy0'
  MOBILE_SDK_APP_ID: '1:570777364216:android:7e0dbafb4baa7973f2fd0d'
