API_HOST_URL: 'https://successlab.ai/'
API_URL_VERSION: 
  BLOCKS: 'v1'
  REGISTRATION: 'v1'
ENVIRONMENT_DISPLAY_NAME: 'SuccessLab'
PLATFORM_NAME: 'SuccessLab'
PHONETIC_PLATFORM_NAME: 'SUCCESSLAB'
PLATFORM_DESTINATION_NAME: 'successlab'
FEEDBACK_EMAIL_ADDRESS: 'feedback@successlab.ai'

ECOMMERCE_URL: 'https://ecommerce.successlab.ai'
DISCOVERY:
  TYPE: native
  NATIVE:
    SEARCH_ENABLED: true
    SUBJECT_FILTER_ENABLED: true
    SUBJECT_DISCOVERY_ENABLED: true
PROGRAM:
  ENABLED: false
YOUTUBE_PLAYER:
  ENABLED: true
  API_KEY: 
ANNOUNCEMENTS_ENABLED: true
BADGES_ENABLED: true
CERTIFICATES_ENABLED: true
COURSE_DATES_ENABLED: true
COURSE_SHARING_ENABLED: false
COURSE_VIDEOS_ENABLED: true
DISCUSSIONS_ENABLED: true
DISCUSSIONS_ENABLE_PROFILE_PICTURE_PARAM: true
PUSH_NOTIFICATIONS: true
NEW_LOGISTRATION_ENABLED: true
REGISTRATION_ENABLED: true
TAB_LAYOUTS_ENABLED: true
USER_PROFILES_ENABLED: true
VIDEO_TRANSCRIPT_ENABLED: true
WHATS_NEW_ENABLED: 
FIREBASE:
  ENABLED: true
  ANALYTICS_SOURCE: true
  CLOUD_MESSAGING_ENABLED: true
  PROJECT_NUMBER: 570777364216
  OAUTH_CLIENT_ID: 570777364216-a2bfnc2h1oto8n4c6e9mf3aq7akk6jh0.apps.googleusercontent.com
  CURRENT_KEY: AIzaSyA5D091QNgvf-Ev1VMscjP6RORQFbo4Hy0
 
GOOGLE:
  ENABLED: false
APP_REVIEWS_ENABLED: true
DOWNLOAD_TO_SD_CARD_ENABLED: true